### ISSUE TITLE
🐶new logo for this 

### ISSUE THREAD

**Issue by Tedko** [DimensionFoundation/PriceDoge#2]
Finish by 3/14. Upload the thing in read me as well.

**Comment by neruthes** [comment]
![pricedog-logo](https://user-images.githubusercontent.com/2139261/54441929-a050cf00-4735-11e9-98db-883b13980fbd.png)

感受一下（

**Comment by neruthes** [comment]
<img width="544" alt="Screen Shot 2019-03-15 at 15 22 18" src="https://user-images.githubusercontent.com/2139261/54442451-97acc880-4736-11e9-85c6-123fb3b15dc1.png">
<img width="460" alt="Screen Shot 2019-03-15 at 15 24 44" src="https://user-images.githubusercontent.com/2139261/54442452-97acc880-4736-11e9-9658-4e038f0c234a.png">
<img width="407" alt="Screen Shot 2019-03-15 at 15 24 49" src="https://user-images.githubusercontent.com/2139261/54442453-98455f00-4736-11e9-9043-202ca293e08c.png">
<img width="354" alt="Screen Shot 2019-03-15 at 15 24 56" src="https://user-images.githubusercontent.com/2139261/54442454-98455f00-4736-11e9-9476-226c864872ce.png">
<img width="443" alt="Screen Shot 2019-03-15 at 15 25 09" src="https://user-images.githubusercontent.com/2139261/54442455-98ddf580-4736-11e9-8809-3556746833f0.png">

**Comment by Tedko** [comment]
我喜欢第一个or倒数第二
