### ISSUE TITLE
私钥出现在了代码库中

### ISSUE THREAD

**Issue by OldPanda** [DimensionFoundation/PriceDoge#3]
https://github.com/DimensionFoundation/PriceDoge/blob/master/extension/key.pem

不确定在这个仓库这样做有没有什么问题，但是建议赶紧 revert

**Comment by Jack-Works** [comment]
你好，谢谢你的关心，如果插件能上扩展商店，那么这个 pem 应该是没什么用的。不过我们现在是自己打包 crx，我们之后会处理的

**Comment by yisiliu** [comment]
fixed. Thanks

**Comment by Jack-Works** [comment]
@yisiliu force push? 这样会不会还在 .git/ 里面留着呢？

**Comment by yisiliu** [comment]
> @yisiliu force push? 这样会不会还在 .git/ 里面留着呢？

git filter-branch 会rewrite revision history
